#!/usr/bin/perl -w

# example should not be included in a 'make test'
# as it will fail
my @tests = (
   't/levmar.t',
   't/liblevmar.t',
   't/interface.t',
   't/thread.t',
   't/chkjac.t',
   't/keeprefs.t',
   't/ndim.t',

);

unlink "err.levtest";

foreach my $test ( @tests ) {
  print "#### $test\n";	
#  system "perl -I ./blib/lib -I ./blib/arch  $test";
  system "perl -I ./blib/lib -I ./blib/arch  $test 2>> ./err.levtest";
}
